---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_sysctl: https://github.com/simp/augeasproviders_sysctl
    docker:
      repo: https://github.com/simp/puppetlabs-docker
      ref: 1.0.1
    iptables: https://github.com/simp/pupmod-simp-iptables
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    simp_docker: "#{source_dir}"
